"""
code_analyser.py — Static analysis bridge between Codex output and ML pipelines
================================================================================
Given any code string (generated by Codex or otherwise), produces:
  - cve_signals    : 17-feature dict for CVE ML (attack vector, CWE flags, etc.)
  - defect_metrics : 22-feature dict for Defect ML (cyclomatic complexity, etc.)

The CVE signal extraction is delegated to the existing analyse_code() in
the CVE ML pipeline (no duplication). Defect metrics are computed here via
lightweight static analysis — no AST parser or external linter required.

Usage:
    from code_analyser import analyse_code_full

    result = analyse_code_full("def login(user): ...")
    print(result["cve_signals"])
    print(result["defect_metrics"])
"""

import re
import os
import sys

# ── Resolve paths ─────────────────────────────────────────────────────────────
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
CVE_ML_DIR   = os.path.join(SCRIPT_DIR, "..", "CVE ML")

# Add CVE ML folder to path so we can import analyse_code() from there
if CVE_ML_DIR not in sys.path:
    sys.path.insert(0, os.path.abspath(CVE_ML_DIR))

from codex_risk_pipeline import analyse_code as _cve_analyse_code  # noqa: E402


# ── Static analysis warnings — code smell patterns ────────────────────────────
_SMELL_CHECKS: list[tuple[re.Pattern, int, str]] = [
    (re.compile(r'\beval\s*\('),                        3, "eval() usage"),
    (re.compile(r'\bexec\s*\('),                        3, "exec() usage"),
    (re.compile(r'except\s*:'),                         2, "bare except"),
    (re.compile(r'\bglobal\s+\w+'),                     1, "global variable"),
    (re.compile(r'print\s*\(.*(?:password|secret|token|key)', re.I), 2, "credential in print"),
    (re.compile(r'\bTODO\b|\bFIXME\b|\bHACK\b|\bXXX\b'),           1, "TODO/FIXME marker"),
    (re.compile(r'assert\s'),                           0, ""),   # counted separately
    (re.compile(r'0x[0-9a-fA-F]{4,}'),                 1, "magic hex constant"),
    (re.compile(r'__import__\s*\('),                    2, "dynamic __import__"),
    # subprocess: +1 base; +2 more if shell=True is present (escalation)
    (re.compile(r'subprocess\.(call|run|Popen)'),       1, "subprocess call"),
    (re.compile(r'subprocess\.\w+\s*\(.*shell\s*=\s*True', re.DOTALL), 2, "subprocess shell=True"),
    (re.compile(r'os\.system\s*\('),                    2, "os.system() call"),
    (re.compile(r'pickle\.(load|loads)\s*\('),          2, "unsafe pickle load"),
    # Unsafe deserialization
    (re.compile(r'yaml\.load\s*\((?!.*Loader\s*=\s*yaml\.(Safe|Full)Loader)'), 2, "unsafe yaml.load"),
    (re.compile(r'dill\.loads?\s*\('),                  2, "unsafe dill deserialization"),
    (re.compile(r'jsonpickle\.decode\s*\('),            2, "unsafe jsonpickle.decode"),
    (re.compile(r'marshal\.loads\s*\('),                2, "unsafe marshal.loads"),
    # XXE via lxml with user-controlled input
    (re.compile(r'lxml'), 1, "lxml XML parsing"),
    (re.compile(r'lxml.*(?:parse|fromstring).*(?:request|input|user|data)', re.DOTALL), 2, "lxml XXE risk"),
    # CSV formula injection
    (re.compile(r'csv\.(writer|DictWriter).*(?:writerow|writerows)', re.DOTALL), 0, ""),  # counted below
    (re.compile(r'(?:name|player|winner).*[=+].*(?:csv|write)', re.I), 1, "CSV formula injection risk"),
    # compile() with dynamic input
    (re.compile(r'\bcompile\s*\('), 2, "compile() with dynamic code"),
]

_PERF_CHECKS: list[tuple[re.Pattern, int, str]] = [
    (re.compile(r'SELECT\s+\*', re.I),                  1, "SELECT * query"),
    (re.compile(r'time\.sleep\s*\('),                   1, "blocking sleep"),
    (re.compile(r'\.append\s*\(.*\)\s*\n.*\.append\s*\('), 1, "repeated appends (use extend)"),
    (re.compile(r'for\s+\w+.*:\s*\n.*for\s+\w+.*:\s*\n.*for'), 1, "triple-nested loop"),
]


# ── Defect metric extractor ───────────────────────────────────────────────────

def extract_defect_metrics(code: str) -> dict:
    """
    Compute software quality metrics from source code.

    Returns all 22 features used by the Defect ML model.
    Features that require version-control history default to neutral values
    (documented inline).

    Feature map:
      Directly computed:  lines_of_code, cyclomatic_complexity, num_functions,
                          num_classes, comment_density, avg_function_length,
                          response_for_class, coupling_between_objects,
                          depth_of_inheritance, test_coverage, lack_of_cohesion,
                          static_analysis_warnings, performance_issues,
                          duplication_percentage, security_vulnerabilities (0 here)
      Historical defaults: past_defects=0, code_churn=0, bug_fix_commits=0,
                           build_failures=0, num_developers=1, commit_frequency=1,
                           developer_experience_years=3 (median)
    """
    lines        = code.splitlines()
    non_empty    = [l for l in lines if l.strip()]
    comment_ln   = [l for l in non_empty if l.strip().startswith("#")]

    loc = len(non_empty)

    # Cyclomatic complexity: count branching keywords + 1
    branch_kw = re.findall(
        r'\b(if|elif|for|while|and|or|not|except|case|assert)\b', code
    )
    cyclomatic = len(branch_kw) + 1

    # Function and class counts
    num_functions = len(re.findall(r'^\s*def\s+\w+', code, re.MULTILINE))
    num_classes   = len(re.findall(r'^\s*class\s+\w+', code, re.MULTILINE))

    # Comment density
    comment_density = len(comment_ln) / max(loc, 1)

    # Average function length (lines per def block until next def/class/EOF)
    func_bodies = re.findall(
        r'(?:^|\n)( {0,8}def\s+\w+.*?)(?=\n {0,8}(?:def|class)\s|\Z)',
        code, re.DOTALL
    )
    avg_fn_len = (
        sum(len(b.splitlines()) for b in func_bodies) / len(func_bodies)
        if func_bodies else 0
    )

    # Static analysis warnings
    warnings = 0
    for pattern, weight, _ in _SMELL_CHECKS:
        if weight > 0 and pattern.search(code):
            warnings += weight
    if cyclomatic > 20:     warnings += 2
    if avg_fn_len  > 50:    warnings += 1
    if comment_density < 0.05 and loc > 30:  warnings += 1

    # Performance issues
    perf_issues = sum(1 for pat, _, _ in _PERF_CHECKS if pat.search(code))

    # Response for class: num_functions + external method calls (capped)
    method_calls       = len(re.findall(r'\w+\.\w+\s*\(', code))
    response_for_class = num_functions + min(method_calls, 20)

    # Coupling: number of import statements
    imports               = re.findall(r'^(?:import|from)\s+\S+', code, re.MULTILINE)
    coupling_between_objects = len(imports)

    # Depth of inheritance: class Foo(Bar) patterns
    depth_of_inheritance = len(re.findall(r'class\s+\w+\s*\(\s*\w+', code))

    # Test coverage estimate
    test_fn_count = len(re.findall(r'def\s+test_\w+', code))
    if num_functions == 0:
        test_coverage = 0.0
    elif test_fn_count > 0:
        test_coverage = min(test_fn_count / num_functions, 1.0)
    else:
        test_coverage = 0.0

    # Lack of cohesion: module-level statements vs total
    module_level_lines = [l for l in lines if l.strip() and not l.startswith(" ")]
    lack_of_cohesion   = len(module_level_lines) / max(loc, 1)

    # Duplication: fraction of non-unique content lines (>10 chars)
    content_lines  = [l.strip() for l in non_empty if len(l.strip()) > 10]
    unique_content = set(content_lines)
    dup_pct = 1 - (len(unique_content) / max(len(content_lines), 1))

    return {
        "lines_of_code":             loc,
        "cyclomatic_complexity":     cyclomatic,
        "num_functions":             num_functions,
        "num_classes":               num_classes,
        "comment_density":           round(comment_density, 3),
        "code_churn":                0,    # version-control only
        "developer_experience_years": 3,  # unknown → median
        "num_developers":            1,
        "commit_frequency":          1,
        "bug_fix_commits":           0,   # version-control only
        "past_defects":              0,   # version-control only
        "test_coverage":             round(test_coverage, 3),
        "duplication_percentage":    round(dup_pct, 3),
        "avg_function_length":       round(avg_fn_len, 1),
        "depth_of_inheritance":      depth_of_inheritance,
        "response_for_class":        response_for_class,
        "coupling_between_objects":  coupling_between_objects,
        "lack_of_cohesion":          round(lack_of_cohesion, 3),
        "build_failures":            0,   # CI/CD only
        "static_analysis_warnings":  warnings,
        "security_vulnerabilities":  0,   # filled by unified analyser below
        "performance_issues":        perf_issues,
    }


# ── Unified code analysis ─────────────────────────────────────────────────────

def analyse_code_full(code: str, instruction: str = "") -> dict:
    """
    Full static analysis of a generated code string.
    Returns a dict with both signal sets ready for the ML pipelines.

    Returned structure:
    {
        "cve_signals"    : {cwe_has_*, attack_vector_encoded, num_cwes, ...}  ← for CVE ML
        "defect_metrics" : {cyclomatic_complexity, static_analysis_warnings, ...}  ← for Defect ML
        "instruction"    : original instruction string
        "smells"         : list of detected code smell descriptions
    }
    """
    cve_signals    = _cve_analyse_code(code)
    defect_metrics = extract_defect_metrics(code)

    # Bridge: CVE security vulnerabilities count feeds into Defect ML feature
    defect_metrics["security_vulnerabilities"] = int(cve_signals.get("num_cwes", 0))

    # Collect human-readable smell descriptions for the report
    smells = []
    for pattern, weight, desc in _SMELL_CHECKS:
        if weight > 0 and pattern.search(code):
            smells.append(desc)
    if defect_metrics["cyclomatic_complexity"] > 20:
        smells.append(f"high cyclomatic complexity ({defect_metrics['cyclomatic_complexity']})")
    if defect_metrics["avg_function_length"] > 50:
        smells.append(f"long functions (avg {defect_metrics['avg_function_length']:.0f} lines)")

    triggered_cwes = [k for k, v in cve_signals.items() if k.startswith("cwe_") and v == 1]

    return {
        "cve_signals":    cve_signals,
        "defect_metrics": defect_metrics,
        "instruction":    instruction,
        "triggered_cwes": triggered_cwes,
        "smells":         smells,
    }


# ── Quick self-test ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    _sample = """
import sqlite3
import os

def get_user(username):
    conn = sqlite3.connect('users.db')
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM users WHERE name = '" + username + "'")
    return cursor.fetchall()

def render_name(name):
    return f"<div>{name}</div>"
"""
    res = analyse_code_full(_sample, instruction="fetch user from DB and render name")
    print("CVE signals :", res["triggered_cwes"])
    print("CWE count   :", res["cve_signals"]["num_cwes"])
    print("Cyclomatic  :", res["defect_metrics"]["cyclomatic_complexity"])
    print("SA warnings :", res["defect_metrics"]["static_analysis_warnings"])
    print("Smells      :", res["smells"])
